### ISSUE TITLE
Recolour chart

### ISSUE THREAD

**Issue by dvnguyen02** [dvnguyen02/DATA301-Project#7]
For this plot here, the colour is very nice. But however, I dont believe the colouring is consistent with other plots. The other plots has blue and orange for kidney stones and no kidney stones. We could change them all to this colour or just blue and orange like what we've been already doing. Which one you prefer? I dont mind
![image_2024-08-30_100349274](https://github.com/user-attachments/assets/12fdd574-83ce-48c7-8d5f-618516ccf11c)

**Comment by ktchufong** [comment]
YEA i actually changed it but havent committed yet ill do now

**Comment by dvnguyen02** [comment]
sweet I will close the case then
